sage -pip install FXrays
sage -pip install hg+https://bitbucket.org/t3m/snappy_manifolds
sage -pip install hg+https://bitbucket.org/t3m/plink
sage -pip install hg+https://bitbucket.org/t3m/gridlink
sage -pip install hg+https://bitbucket.org/t3m/spherogram
sage -pip install hg+https://bitbucket.org/t3m/snappy
sage -pip install hg+https://bitbucket.org/t3m/pe
sage -pip install flipper
sage -pip install curver
#sage -python -m snappy.test
